/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.View;

import banco.Dao.connectDAO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alunos
 */
public class ClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteFrame
     */
    public ClienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_agencias = new javax.swing.JMenu();
        jMenuItem5_incluir = new javax.swing.JMenuItem();
        jMenuItem6_alterar = new javax.swing.JMenuItem();
        jMenuItem7_excluir = new javax.swing.JMenuItem();
        jMenu3_clientes = new javax.swing.JMenu();
        jMenuItem22_incluir = new javax.swing.JMenuItem();
        jMenuItem33_alterar = new javax.swing.JMenuItem();
        jMenuItem44_excluir = new javax.swing.JMenuItem();
        jMenu4_contas_correntes = new javax.swing.JMenu();
        jMenuItem55_incluir = new javax.swing.JMenuItem();
        jMenuItem66_alterar = new javax.swing.JMenuItem();
        jMenuItem77_excluir = new javax.swing.JMenuItem();
        jMenu5_historicos = new javax.swing.JMenu();
        jMenu6_movimentacao = new javax.swing.JMenu();
        jMenuItem8_incluir = new javax.swing.JMenuItem();
        jMenuItem9_alterar = new javax.swing.JMenuItem();
        jMenuItem10_excluir = new javax.swing.JMenuItem();
        jMenu7_usuarios = new javax.swing.JMenu();
        jMenuItem11_incluir = new javax.swing.JMenuItem();
        jMenuItem12_alterar = new javax.swing.JMenuItem();
        jMenuItem13_excluir = new javax.swing.JMenuItem();
        jMenu1_funcionarios = new javax.swing.JMenu();
        jMenuItem1_incluir = new javax.swing.JMenuItem();
        jMenuItem2_alterar = new javax.swing.JMenuItem();
        jMenuItem3_excluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jMenu1_agencias.setText("Agências");
        jMenu1_agencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1_agenciasMouseClicked(evt);
            }
        });
        jMenu1_agencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1_agenciasActionPerformed(evt);
            }
        });

        jMenuItem5_incluir.setText("Incluir");
        jMenuItem5_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_incluirActionPerformed(evt);
            }
        });
        jMenu1_agencias.add(jMenuItem5_incluir);

        jMenuItem6_alterar.setText("Alterar");
        jMenuItem6_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_alterarActionPerformed(evt);
            }
        });
        jMenu1_agencias.add(jMenuItem6_alterar);

        jMenuItem7_excluir.setText("Excluir");
        jMenuItem7_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_excluirActionPerformed(evt);
            }
        });
        jMenu1_agencias.add(jMenuItem7_excluir);

        jMenuBar1.add(jMenu1_agencias);

        jMenu3_clientes.setText("Clientes");

        jMenuItem22_incluir.setText("Incluir");
        jMenuItem22_incluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem22_incluirMouseClicked(evt);
            }
        });
        jMenuItem22_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22_incluirActionPerformed(evt);
            }
        });
        jMenu3_clientes.add(jMenuItem22_incluir);

        jMenuItem33_alterar.setText("Alterar");
        jMenuItem33_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem33_alterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem33_alterarMouseEntered(evt);
            }
        });
        jMenuItem33_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33_alterarActionPerformed(evt);
            }
        });
        jMenu3_clientes.add(jMenuItem33_alterar);

        jMenuItem44_excluir.setText("Excluir");
        jMenuItem44_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44_excluirActionPerformed(evt);
            }
        });
        jMenu3_clientes.add(jMenuItem44_excluir);

        jMenuBar1.add(jMenu3_clientes);

        jMenu4_contas_correntes.setText("Contas Correntes");
        jMenu4_contas_correntes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4_contas_correntesMouseClicked(evt);
            }
        });
        jMenu4_contas_correntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4_contas_correntesActionPerformed(evt);
            }
        });

        jMenuItem55_incluir.setText("Incluir");
        jMenuItem55_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem55_incluirActionPerformed(evt);
            }
        });
        jMenu4_contas_correntes.add(jMenuItem55_incluir);

        jMenuItem66_alterar.setText("alterar");
        jMenuItem66_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem66_alterarActionPerformed(evt);
            }
        });
        jMenu4_contas_correntes.add(jMenuItem66_alterar);

        jMenuItem77_excluir.setText("Excluir");
        jMenuItem77_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem77_excluirActionPerformed(evt);
            }
        });
        jMenu4_contas_correntes.add(jMenuItem77_excluir);

        jMenuBar1.add(jMenu4_contas_correntes);

        jMenu5_historicos.setText("Históricos");
        jMenu5_historicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5_historicosMouseClicked(evt);
            }
        });
        jMenu5_historicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5_historicosActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5_historicos);

        jMenu6_movimentacao.setText("Movimentação");
        jMenu6_movimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6_movimentacaoMouseClicked(evt);
            }
        });

        jMenuItem8_incluir.setText("Incluir");
        jMenuItem8_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_incluirActionPerformed(evt);
            }
        });
        jMenu6_movimentacao.add(jMenuItem8_incluir);

        jMenuItem9_alterar.setText("Alterar");
        jMenuItem9_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_alterarActionPerformed(evt);
            }
        });
        jMenu6_movimentacao.add(jMenuItem9_alterar);

        jMenuItem10_excluir.setText("Excluir");
        jMenuItem10_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10_excluirActionPerformed(evt);
            }
        });
        jMenu6_movimentacao.add(jMenuItem10_excluir);

        jMenuBar1.add(jMenu6_movimentacao);

        jMenu7_usuarios.setText("Usuários");
        jMenu7_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7_usuariosMouseClicked(evt);
            }
        });

        jMenuItem11_incluir.setText("Incluir");
        jMenuItem11_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11_incluirActionPerformed(evt);
            }
        });
        jMenu7_usuarios.add(jMenuItem11_incluir);

        jMenuItem12_alterar.setText("Alterar");
        jMenuItem12_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12_alterarActionPerformed(evt);
            }
        });
        jMenu7_usuarios.add(jMenuItem12_alterar);

        jMenuItem13_excluir.setText("Excluir");
        jMenuItem13_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13_excluirActionPerformed(evt);
            }
        });
        jMenu7_usuarios.add(jMenuItem13_excluir);

        jMenuBar1.add(jMenu7_usuarios);

        jMenu1_funcionarios.setText("Funcionários");

        jMenuItem1_incluir.setText("Incluir");
        jMenuItem1_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_incluirActionPerformed(evt);
            }
        });
        jMenu1_funcionarios.add(jMenuItem1_incluir);

        jMenuItem2_alterar.setText("Alterar");
        jMenuItem2_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_alterarActionPerformed(evt);
            }
        });
        jMenu1_funcionarios.add(jMenuItem2_alterar);

        jMenuItem3_excluir.setText("Excluir");
        jMenuItem3_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_excluirActionPerformed(evt);
            }
        });
        jMenu1_funcionarios.add(jMenuItem3_excluir);

        jMenuBar1.add(jMenu1_funcionarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1_agenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1_agenciasActionPerformed

    }//GEN-LAST:event_jMenu1_agenciasActionPerformed

    private void jMenu1_agenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1_agenciasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1_agenciasMouseClicked

    private void jMenu4_contas_correntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4_contas_correntesActionPerformed

    }//GEN-LAST:event_jMenu4_contas_correntesActionPerformed

    private void jMenu4_contas_correntesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4_contas_correntesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4_contas_correntesMouseClicked

    private void jMenu5_historicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5_historicosMouseClicked
        banco.View.Historicos historicos = new banco.View.Historicos();
        historicos.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu5_historicosMouseClicked

    private void jMenu6_movimentacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6_movimentacaoMouseClicked

    }//GEN-LAST:event_jMenu6_movimentacaoMouseClicked

    private void jMenu7_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7_usuariosMouseClicked

    }//GEN-LAST:event_jMenu7_usuariosMouseClicked

    private void jMenuItem22_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22_incluirActionPerformed
        String operacao = "Incluir";
        CadastroClientes cadastroclientes = new CadastroClientes(operacao);
        cadastroclientes.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22_incluirActionPerformed

    private void jMenuItem22_incluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem22_incluirMouseClicked

    }//GEN-LAST:event_jMenuItem22_incluirMouseClicked

    private void jMenuItem33_alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem33_alterarMouseClicked

    }//GEN-LAST:event_jMenuItem33_alterarMouseClicked

    private void jMenuItem33_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33_alterarActionPerformed
        String operacao = "Alterar";
        CadastroClientes alterar = new CadastroClientes(operacao);
        alterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem33_alterarActionPerformed

    private void jMenuItem44_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44_excluirActionPerformed
        String operacao = "Excluir";
        CadastroClientes excluir = new CadastroClientes(operacao);
        excluir.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem44_excluirActionPerformed

    private void jMenuItem6_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_alterarActionPerformed
        String operacao = "Alterar";
        AgenciasView alterar = new AgenciasView(operacao);
        alterar.setVisible(true);//        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6_alterarActionPerformed

    private void jMenuItem55_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem55_incluirActionPerformed
        String operacao = "Incluir";
        ContaCorrenteView incluir = new ContaCorrenteView(operacao); //principal
        incluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem55_incluirActionPerformed

    private void jMenuItem8_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_incluirActionPerformed
        String operacao = "Incluir";
        MovimentacaoView incluir = new MovimentacaoView(operacao);
        incluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem8_incluirActionPerformed

    private void jMenuItem11_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11_incluirActionPerformed
        String operacao = "Incluir";
        UsuariosView incluir = new UsuariosView(operacao);
        incluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem11_incluirActionPerformed

    private void jMenuItem66_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem66_alterarActionPerformed
        String operacao = "Alterar";
        ContaCorrenteView alterar = new ContaCorrenteView(operacao);
        alterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem66_alterarActionPerformed

    private void jMenuItem9_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_alterarActionPerformed
        String operacao = "Alterar";
        MovimentacaoView alterar = new MovimentacaoView(operacao);
        alterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem9_alterarActionPerformed

    private void jMenuItem12_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12_alterarActionPerformed
        String operacao = "Alterar";
        UsuariosView alterar = new UsuariosView(operacao);
        alterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem12_alterarActionPerformed

    private void jMenuItem77_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem77_excluirActionPerformed
        String operacao = "Excluir";
        ContaCorrenteView excluir = new ContaCorrenteView(operacao);
        excluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem77_excluirActionPerformed

    private void jMenuItem10_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10_excluirActionPerformed
        String operacao = "Excluir";
        MovimentacaoView excluir = new MovimentacaoView(operacao);
        excluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem10_excluirActionPerformed

    private void jMenuItem13_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13_excluirActionPerformed
        String operacao = "Excluir";
        UsuariosView excluir = new UsuariosView(operacao);
        excluir.setVisible(true);
    }//GEN-LAST:event_jMenuItem13_excluirActionPerformed

    private void jMenuItem5_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_incluirActionPerformed
        String operacao = "Incluir";
        AgenciasView incluir = new AgenciasView(operacao);
        incluir.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5_incluirActionPerformed

    private void jMenuItem7_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_excluirActionPerformed
        String operacao = "Excluir";
        AgenciasView excluir = new AgenciasView(operacao);
        excluir.setVisible(true);//
    }//GEN-LAST:event_jMenuItem7_excluirActionPerformed

    private void jMenu5_historicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5_historicosActionPerformed

    }//GEN-LAST:event_jMenu5_historicosActionPerformed

    private void jMenuItem33_alterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem33_alterarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem33_alterarMouseEntered

    private void jMenuItem1_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_incluirActionPerformed
        String operacao = "Incluir";
        Funcionarios funcionarios = new Funcionarios(operacao);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem1_incluirActionPerformed

    private void jMenuItem2_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_alterarActionPerformed
        String operacao = "Alterar";
        Funcionarios funcionarios = new Funcionarios(operacao);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem2_alterarActionPerformed

    private void jMenuItem3_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_excluirActionPerformed
        String operacao = "Excluir";
        Funcionarios funcionarios = new Funcionarios(operacao);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem3_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1_agencias;
    private javax.swing.JMenu jMenu1_funcionarios;
    private javax.swing.JMenu jMenu3_clientes;
    private javax.swing.JMenu jMenu4_contas_correntes;
    private javax.swing.JMenu jMenu5_historicos;
    private javax.swing.JMenu jMenu6_movimentacao;
    private javax.swing.JMenu jMenu7_usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10_excluir;
    private javax.swing.JMenuItem jMenuItem11_incluir;
    private javax.swing.JMenuItem jMenuItem12_alterar;
    private javax.swing.JMenuItem jMenuItem13_excluir;
    private javax.swing.JMenuItem jMenuItem1_incluir;
    private javax.swing.JMenuItem jMenuItem22_incluir;
    private javax.swing.JMenuItem jMenuItem2_alterar;
    private javax.swing.JMenuItem jMenuItem33_alterar;
    private javax.swing.JMenuItem jMenuItem3_excluir;
    private javax.swing.JMenuItem jMenuItem44_excluir;
    private javax.swing.JMenuItem jMenuItem55_incluir;
    private javax.swing.JMenuItem jMenuItem5_incluir;
    private javax.swing.JMenuItem jMenuItem66_alterar;
    private javax.swing.JMenuItem jMenuItem6_alterar;
    private javax.swing.JMenuItem jMenuItem77_excluir;
    private javax.swing.JMenuItem jMenuItem7_excluir;
    private javax.swing.JMenuItem jMenuItem8_incluir;
    private javax.swing.JMenuItem jMenuItem9_alterar;
    // End of variables declaration//GEN-END:variables
}
